commerce_product.commerce_product_type.*:
  type: config_entity
  label: 'Product type'
  mapping:
    id:
      type: string
      label: 'Type'
    label:
      type: label
      label: 'Label'
    digital:
      type: boolean
      label: 'Products of this type represent digital services.'
    description:
      type: text
      label: 'Description'
    variationType:
      type: string
      label: 'Variation type'

commerce_product.commerce_product_variation_type.*:
  type: config_entity
  label: 'Product variation type'
  mapping:
    id:
      type: string
      label: 'Type'
    label:
      type: label
      label: 'Label'
    lineItemType:
      type: string
      label: 'Line item type'

field.field.*.*.*.third_party.commerce_product:
  type: mapping
  label: 'Product attributes'
  mapping:
    attribute_field:
        type: boolean
        label: 'Whether or not this field should be used as a product attribute'
    attribute_widget:
        type: string
        label: 'The widget to use for the product attribute'
    attribute_widget_title:
        type: label
        label: 'The title of the product attribute for the Add to Cart form'

action.configuration.publish_product_action:
  type: action_configuration_default
  label: 'Configuration for the Publish product action'

action.configuration.unpublish_product_action:
  type: action_configuration_default
  label: 'Configuration for the Unpublish product action'
